replicaCount: 1
name: GIT-TECHSTACK

probe:
  delayseconds: 10

image:
  registry: hub.docker.com   ##### TO BE ADDED AFTER UPLOAD
  repository: shajushaik/git:1  ##### TO BE ADDED AFTER UPLOAD
  pullPolicy: IfNotPresent
  tag: "1"

#imagePullSecrets: []

podAnnotations: {}

#podSecurityContext: {}
  # fsGroup: 2000


service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
   cpu: 500m
   memory: 512Mi

# LivenessProbe
livenessProbe:
  httpGet:
    path: /  # ------------NEED TO ADD --------------
    port: 
  initialDelaySeconds: 5

# ReadinessProbe
readinessProbe:
  httpGet:
    path: /  #----------NEED TO ADD-----------------
    port: 
  initialDelaySeconds: 5

#securityContext:
  # fsGroup: 0
  #runAsUser: 1000

#autoscaling:
#  enabled: true
  #minReplicas: 1
  #maxReplicas: 2
  #targetCPUUtilizationPercentage: 80

#nodeSelector: {}

#tolerations: []

#affinity: {}