apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gittechstack.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gittechstack.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gittechstack.selectorLabels" . | nindent 8 }}
    spec:
      #{{- with .Values.imagePullSecrets }}
      #imagePullSecrets:
        #{{- toYaml . | nindent 8 }}
      #{{- end }}
      #securityContext:
        #{{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
         -name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: 
              port: http
            timeoutSeconds: 5
            periodSeconds: 10
            initialDelaySeconds: {{ .Values.probe.delayseconds }} 
          readinessProbe:
            httpGet:
              path: 
              port: http
            timeoutSeconds: 5
            periodSeconds: 10
            initialDelaySeconds: {{ .Values.probe.delayseconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}